version: '3.9'
services:
  job_offer:
    container_name: 'job_offer'
    build: ./job_offer
    ports:
      - "7000:7000"
    depends_on:
      - database_job_offer
    networks:
      - job_offer_network
    environment:
      - spring.datasource.url=jdbc:postgresql://database_job_offer:5433/offer
  database_job_offer:
    container_name: 'database_job_offer'
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: offer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbstore:/var/lib/postgres
    networks:
      - job_offer_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - job_offer_network

volumes:
  dbstore:
  pgadmin-data:

networks:
  job_offer_network: